
# ?????????? ? yaml

# ?????????? ????????? ?? ?????? ????????????? ?????? ??????????? ?????????

# ???? ??????? ????????? ??????? ? ????????? ?.?. ???????? application-local ? ?????????? ???????????

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres # ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=postgres # ${DB_USERNAME:postgres}
spring.datasource.password=postgres # ${DB_PASSWORD:postgres}

# ?????? ????????????, ????????? ??? ? shema.sql ??? ? shema.sql ??????? ????? ? ??? ?????????(???????, ???????????

# ????????? ? liquibase)
spring.jpa.generate-ddl=true
server.port=8080